### ISSUE TITLE
License

### ISSUE THREAD

**Issue by refi64** [JohnEarnest/ok#10]
What is ok's license? There is no file labeled COPYING or LICENSE, and I can't find any info in oK.js.

**Comment by JohnEarnest** [comment]
It doesn't have one yet, as I generally wait for someone to ask. I prefer highly permissive licenses, such as MIT or the WTFPL. Do you have a preference?

**Comment by refi64** [comment]
@JohnEarnest I like MIT-like licenses, too, but I don't really have a specific request.
