### ISSUE TITLE
Android display bug

### ISSUE THREAD

**Issue by effbiae** [JohnEarnest/ok#100]
![Screenshot_20220211-160119_Chrome](https://user-images.githubusercontent.com/654879/153540064-248e7122-78f5-449e-a583-ecae4e70fae6.jpg)

Output window only half of allocated space (see image)

**Comment by JohnEarnest** [comment]
I seem to be able to reproduce in Chrome on OSX. Please give the above a spin and see if it works for you.

**Comment by effbiae** [comment]
perfect! all fixed

**Comment by JohnEarnest** [comment]
Great! Thanks for the bug report.
