### ISSUE TITLE
ike audio context

### ISSUE THREAD

**Issue by ktye** [JohnEarnest/ok#102]
is that correct? https://github.com/JohnEarnest/ok/blob/gh-pages/ike/audio.js#L45
```js
if (!audio) {
	if (typeof AudioContext !== 'undefined') {
//                              ^^^
		audio = new AudioContext();
	}
	else if (typeof webkitAudioContext !== 'undefined') {
		audio = new webkitAudioContext();
	}
}
```

shouldn't it be `typeof AudioContext === 'undefined'` ?

**Comment by JohnEarnest** [comment]
If the class is _not_ undefined, I want to produce an instance of it.
