### ISSUE TITLE
Default branch?

### ISSUE THREAD

**Issue by muratg** [JohnEarnest/ok#14]
Does it make sense to make a default branch on GH that's up to date? Currently `master` is the default branch which doesn't have the other changes that `gh-pages` have. Perhaps create a `dev` branch and make it default for folks to clone.

**Comment by JohnEarnest** [comment]
Presently the default branch in github for this project is already `gh-pages`, which must be used if I wish for my changes to be reflected on `http://johnearnest.github.io/ok/`. It would complicate my workflow to work from `master` instead for no real benefit, and I don't see how adding a third `dev` branch would simplify anything.

**Comment by muratg** [comment]
Cool, for some reason I thought `master` was the default yesterday. Closing this one.
