### ISSUE TITLE
Explaine iKe's bitmap a bit more

### ISSUE THREAD

**Issue by refi64** [JohnEarnest/ok#18]
> The bitmap is a matrix of indices into the palette.

I have _no_ clue what the heck this is supposed to mean.

**Comment by JohnEarnest** [comment]
A matrix is a list of lists in which each inner list has the same length- a "rectangular" array.

The [palette](https://en.wikipedia.org/wiki/Palette_%28computing%29) is a list of colors ([DOM colors](http://www.w3schools.com/jsref/prop_style_color.asp) that a browser can understand, like `#FFCA74`, represented as strings).

The numbers in the matrix are the indices of colors in the palette- that is, each number in the matrix corresponds to the position of a color in the palette. Conceptually iKe evaluates `palette@bitmap` and then renders the resulting matrix as a rectangular image, one pixel per matrix element.

I invite you to refer to some of the example programs.

**Comment by refi64** [comment]
> The numbers in the matrix are the indices of colors in the palette- that is, each number in the matrix corresponds to the position of a color in the palette. Conceptually iKe evaluates `palette@bitmap` and then renders the resulting matrix as a rectangular image, one pixel per matrix element.

Ahh..._this_ is the part I didn't get. It might be worth adding this longer explanation to iKe's README.

Also, I did read some of the examples. It didn't help. :)
