### ISSUE TITLE
JS error when printing a function

### ISSUE THREAD

**Issue by refi64** [JohnEarnest/ok#19]
```
`0:{x}
```

gives:

```
Converting circular structure to JSON
```

**Comment by JohnEarnest** [comment]
The real K5 doesn't support printing functions:

```
  `0:{x}
ERROR: length
`0:{x}
 ^
```

Kona and K2 don't support printing functions:

```
  `0:{x}
type error
`0:{x}
 ^
```

I don't think there's any reasonable expectation of that operation working.

**Comment by refi64** [comment]
I didn't necessarily expect it to work. I just expected oK to give an error, not JavaScript. :)
