### ISSUE TITLE
question about 0:

### ISSUE THREAD

**Issue by ngn** [JohnEarnest/ok#21]
Is there publicly available doc about what it does in K5? In oK the [in-browser `0:`](https://github.com/JohnEarnest/ok/blob/4be6e9fcdaf5955c1ae228b4b9268851c45a827a/index.html#L157) [fetches a URL](https://github.com/JohnEarnest/ok/blob/4be6e9fcdaf5955c1ae228b4b9268851c45a827a/index.html#L371-L380).  The [REPL's `0:`](https://github.com/JohnEarnest/ok/blob/4be6e9fcdaf5955c1ae228b4b9268851c45a827a/repl.js#L43) reads/writes to stdio but [the todo](https://github.com/JohnEarnest/ok/blob/4be6e9fcdaf5955c1ae228b4b9268851c45a827a/repl.js#L26) next to it says it should work with files.  The [manual](https://github.com/JohnEarnest/ok/blob/a416af46354353070bd0a5b2cd150bf810717931/Manual.md) has no info about it.  [`k.txt`](http://kparc.com/k.txt) just says "0: file r/w(text)".  [kx's wiki](http://code.kx.com/wiki/Reference/ZeroColon) describes the format only in the dyadic case.
I'm particularly interested in whether `0:` must be able to read from stdin synchronously.

**Comment by JohnEarnest** [comment]
For the record, the reason IO verbs are not currently documented in the oK manual is that they are modular- the interpreter itself doesn't provide the facilities and any individual frontend like the browser REPL or iKe can supply IO functions that are appropriate. In the case of the browser REPL there is a brief description of the built in IO verbs [here](https://github.com/JohnEarnest/ok#trying-ok) in the readme.

There's no official public documentation on the behavior of the real k5 IO verbs aside from k.txt to my knowledge. As with most of the semantics of oK what I know is based on experimentation and the example programs I've been able to find. I'm not really sure k5 can read from stdin at all. `0:` reads from files synchronously and apparently if you give it a directory path it gives you a file listing:

```
je@kbox:~$ echo "2+3" > test.txt
je@kbox:~$ ls
k  off  test.txt
je@kbox:~$ rlwrap ./k
2015.04.05 (c) arthur whitney

 0:"test.txt"
,"2+3"
 * 0:"test.txt"
"2+3"
 .* 0:"test.txt"
5
 .* 0:`
ERROR: rank
.* 0:`
   ^
 0:""
(,"k";"off";"test.txt")
```

As I described in #11 k5 is presently invite-only and closed-source but it's fairly easy to obtain a copy to play around with if you ask Arthur Whitney. If there's anything else you'd like me to give a try, let me know.

**Comment by ngn** [comment]
Thanks.  The reason I was asking was because I'd like to experiment with a REPL based on Node's libreadline wrapper instead of [your workaround](https://github.com/JohnEarnest/ok/blob/4be6e9fcdaf5955c1ae228b4b9268851c45a827a/repl.js#L20-L24) for Node's lack of a `readlineSync()`.  The libreadline wrapper emits events for lines typed by the user, but sadly can't do the synchronous read that's required when `ok.setIO()`'s hook gets called.  However, reading from a file or listing a directory should be fine.
I've got a copy of k from last year.  It doesn't support symbols ("names"?) as args to `0:` and it doesn't list dirs, but otherwise works as you showed above.
