### ISSUE TITLE
"outer product each" doesn't work

### ISSUE THREAD

**Issue by ngn** [JohnEarnest/ok#24]
Repro:

``` k
 a:(!3;!4)
(0 1 2
 0 1 2 3)
 a*/:\:'a
invalid arguments to ' [(0 1 2
 0 1 2 3)  */:\: (valence 1), (0 1 2
 0 1 2 3)]
```

I was expecting:

``` k
((0 0 0
  0 1 2
  0 2 4)
 (0 0 0 0
  0 1 2 3
  0 2 4 6
  0 3 6 9))
```

**Comment by JohnEarnest** [comment]
Seems to have just been a missing case in the adverb dispatch table. Apparently I've never exercised an expression of that form before.

**Comment by ngn** [comment]
Indeed it's an obscure case.  Thanks for the quick fix.
