### ISSUE TITLE
JS error when trying to assign result of \t

### ISSUE THREAD

**Issue by refi64** [JohnEarnest/ok#25]
```
  a:\t
Cannot read property 'sticky' of null
```

I didn't expect this to work, though...

BTW, I seem to have this knack for getting JS errors from doing weird stuff. :)

**Comment by JohnEarnest** [comment]
The actual cause of the problem was using an assignment operator with no right expression. You could produce the same problem with simply

```
a:
```

The sequence `\t` is a repl command only and cannot be used as part of an expression.

**Comment by refi64** [comment]
@JohnEarnest Well, I figured that much out when I tried to print `\t`. :)
