### ISSUE TITLE
scan with matrix instead of function

### ISSUE THREAD

**Issue by ngn** [JohnEarnest/ok#28]
This is a suggestion for an enhancement.
Wouldn't it be nice if `a\`, where `a` is a matrix, would behave like `{a[x;y]}\`

**Comment by JohnEarnest** [comment]
@ngn reviewing this, I don't think this idea fits in given k5's pack/unpack overloads. Given `l` (list) and `a` (atom), `l/` and `l\` should clearly relate to one another in this case just as over/scan do in other situations, but `l\a` is already "unpack" and `l/l` is already "pack".

Feel free to reopen if I'm misunderstanding.
