### ISSUE TITLE
repl drops first 2 chars when assigning f1/f2/'  to a variable

### ISSUE THREAD

**Issue by buffis** [JohnEarnest/ok#3]
+/+/' ((2 3);(3 5))
13
  f:+/+/'
+/'
  f ((2 3);(3 5))
5 8

Produces 13 in Kona and kdb

**Comment by JohnEarnest** [comment]
Thanks for the bug report! Your example works as expected now. Are there any similar cases which appear to be broken?

**Comment by buffis** [comment]
Nha, seems to work now!
