### ISSUE TITLE
manual.md should say that  #[a:3;b:17] yields 2

### ISSUE THREAD

**Issue by jordancurve** [JohnEarnest/ok#42]
manual.md says that  #[a:3;b:17] yields 17 17 17, but it actually yields 2.

**Comment by JohnEarnest** [comment]
Looks like a regression. That particular example is problematic because it demonstrates potential parse ambiguity between dyadic function application and monadic application to a dictionary literal. Observe how whitespace impacts behavior in the official k5 interpreter:

```
 #[a:3;b:17]
17 17 17

 # [a:3;b:17]
2
```
