### ISSUE TITLE
`_` with out-of-bounds yields JS error

### ISSUE THREAD

**Issue by FireyFly** [JohnEarnest/ok#44]
As seen in the sample below, `l_l` throws a JS error when given out-of-bounds values as the left argument. Not sure what the proper behaviour is (I was hoping for trailing too-high values to be ignored).

```
 0 6_!5
Cannot read property 't' of undefined
```

**Comment by refi64** [comment]
In K5, it gives a length error:

```
ryan@DevPC-LX:~/stuff$ rlwrap k5
2015.04.05 (c) arthur whitney
 0 6_!5
ERROR: length
0 6_!5
   ^

ryan@DevPC-LX:~/stuff$ 
```

**Comment by FireyFly** [comment]
I see. I guess it shouldn't yield a JS error though, but rather check for the out-of-bounds condition and throw its own error.
