### ISSUE TITLE
Manual says that $`beef returns "beef", but it returns "`beef"

### ISSUE THREAD

**Issue by darkf** [JohnEarnest/ok#45]
From oK:

```
$`beef
"`beef"
```

From the manual:

```
  $`beef
"beef"
```

**Comment by darkf** [comment]
This is because `format` gives a representation of symbols with the backtick, which is used in kfmt. `"beef"` seems to be the desired behavior (from kdb, anyway).

**Comment by JohnEarnest** [comment]
In K5:

```
 $`beef
"beef"
```

So, the behavior you expect should be what happens. The manual is right, oK's behavior is wrong.

**Comment by JohnEarnest** [comment]
As a side note, as mentioned in #8 I am not aware of a way to convert a string into a symbol; It's a little asymmetrical that you can still easily convert a symbol to an equivalent string. If any onlookers with a copy of k5 handy can find or point out a way to go the other way it may be a missing oK feature or at the least deserve a brief mention in the manual

**Comment by ngn** [comment]
There's an obvious way which already works in oK: `."`",`

**Comment by JohnEarnest** [comment]
Good point, @ngn - constructing strings to `eval` is very flexible.
