### ISSUE TITLE
refs vs values

### ISSUE THREAD

**Issue by ngn** [JohnEarnest/ok#63]
Indexed assignment treats variables as refs rather than values, i.e. it modifies them in place even when their refcount is >1

``` k
oK v0.1
 a:b:1 2 3
1 2 3
 b[2]:4
1 2 4
 a
1 2 4
```

I was expecting `a` to remain unchanged. Similarly with dicts:

``` k
 a:b:[k:0]
[k:0]
 b[`k]:1
[k:1]
 a
[k:1]
```

**Comment by JohnEarnest** [comment]
K6 has the following behavior:

```
 a:b:1 2 3
 b[2]:4
 b
1 2 4
 a
1 2 3

 a:b:(,`k)!,0
 b[`k]:1
 b
(,`k)!,1
 a
(,`k)!,0
```

**Comment by JohnEarnest** [comment]
Should be fixed.

At some point I need to totally rework the implementation of amend/dmend- they're a total mess.
