### ISSUE TITLE
code samples in k5/k6

### ISSUE THREAD

**Issue by wizzard0** [JohnEarnest/ok#64]
where can one find code in k5/k6 as opposed to k4? and maybe some comparison too

**Comment by JohnEarnest** [comment]
The only canonical source online for this type of thing is [kparc](http://kparc.com/z/). Some of the examples here work properly in oK and some depend on features which have not been implemented properly yet. (I also suspect one or two _did_ work in k5/k6 but have been broken by subsequent changes...)

I get my information primarily from experimenting with a copy of the current k6 interpreter provided to me by Arthur Whitney. My [manual](https://github.com/JohnEarnest/ok/blob/gh-pages/docs/Manual.md) is generally a good description of the features I've discovered/implemented so far. The short version is that k5 and k6 are more like k3 than they are like k4. Simpler type system, many features trimmed down or removed. K6 does, however, include vastly improved support for dictionaries relative to k3 with many useful overloads and generalizations of operators for them.

**Comment by wizzard0** [comment]
Just curious: how does performance of K6 compare to K4?

**Comment by JohnEarnest** [comment]
If there's a specific program you'd like me to try in k6, I'd be happy to run it for you.

If you want to do your own experimentation, you can contact Arthur at arthur.whitney@gmail.com and ask him nicely for a copy of k6.

**Comment by JohnEarnest** [comment]
Since there are no further requests, I think it's safe to close this now. Feel free to reopen if you deem it necessary.
