### ISSUE TITLE
x!y doesn't check for errors when part of a larger expression

### ISSUE THREAD

**Issue by ngn** [JohnEarnest/ok#67]
```k
 `a`b!`c`d`e
length error.
 #`a`b!`c`d`e
3
```

**Comment by JohnEarnest** [comment]
Hm. Actually I think the issue is that `!` doesn't check the lengths of vectors at all, but the prettyprinter chokes on formatting symbol-keyed dictionaries with uneven key/val vectors:

     1 2!`c`d`e
    1 2!`c`d`e
