### ISSUE TITLE
2 3#""

### ISSUE THREAD

**Issue by ngn** [JohnEarnest/ok#68]
```
 2 3#"" /or an empty list of any other type
Cannot read property 't' of undefined
```

**Comment by ngn** [comment]
now it returns
```
((()
  ()
  ())
 (()
  ()
  ()))
```
shouldn't it be
```
("   "
 "   ")
```
?

**Comment by JohnEarnest** [comment]
In k6:

```
 2 3#()
(("";"";"");("";"";""))
 
 2 3#""
("   ";"   ")
```

However, as far as oK is concerned, these cases are indistinguishable because it doesn't track vector types; `()~""`. I think the current behavior is the most reasonable thing I can do given the existing type system.

**Comment by ngn** [comment]
I see. Thanks for explaining.
