### ISSUE TITLE
[question] which of the various K implementations use lexical scope?

### ISSUE THREAD

**Issue by hoosierEE** [JohnEarnest/ok#75]
Playing with iKe it appears (to my delight!) to support lexically-scoped closures:

```
greet:{[lang]
 greeting: $[lang~"eng";"hello ";"hola "]
 {greeting,x}}

hi:greet["eng"]
hey:greet["asdf"]

hey["bob"] / "hello bob"
hi["bob"]  / "hola bob"
```

Is this a first for K implementations?  I was under the impression that Whitney's K and Q implementations used dynamic scoping and did not support closures.

**Comment by ngn** [comment]
I think you swapped `hi` and `hey` in the last two lines.

Terminology nitpick: lack of closures doesn't mean dynamic scoping. Dynamic scoping is when the callee can see variables from the _caller's context_. That's not the case in k. In (the original) k functions can see only local and _global_ variables and nothing in between, so scoping is still lexical, albeit restricted.

**Comment by hoosierEE** [comment]
Thanks for the clarification, I was indeed conflating the two concepts.
