### ISSUE TITLE
?d^?d no longer finds non-unique elements

### ISSUE THREAD

**Issue by jordancurve** [JohnEarnest/ok#78]
In https://codegolf.stackexchange.com/a/60648/84951 (2015), JohnEarnest wrote:

```
  nu: {?x^?x}
  nu'(();-1 0 1;1 1;3 0 0 1 1 0 5 3;-34 0 1 -34 4 8 4)
(()
 ()
 ,1
 0 1 3
 -34 4)
```

Now, though, the [oK REPL](http://johnearnest.github.io/ok/index.html) gives all blanks for that input:

```
Welcome to oK v0.1
(inspired by K5)
  nu: {?x^?x}

{[x]?x^?x}
    nu'(();-1 0 1;1 1;3 0 0 1 1 0 5 3;-34 0 1 -34 4 8 4)

(()
 ()
 ()
 ()
 ())
```

**Comment by ngn** [comment]
`x^y` [was changed](https://github.com/JohnEarnest/ok/blob/gh-pages/docs/Fromk5Tok6.md#except-removes-all-done) to remove all occurrences

a possible replacement is `nu:{?x@,/1_'.=x}`, unfortunately longer

**Comment by JohnEarnest** [comment]
@ngn's reply is accurate.

It's too bad we lost a cute idiom. I brought it up to Arthur during the k5/k6 transition and as it turned out he was totally unaware that except had been "broken" as I discovered in k5.
