### ISSUE TITLE
`"hello" returns "hello" instead of `hello

### ISSUE THREAD

**Issue by muratg** [JohnEarnest/ok#8]

**Comment by JohnEarnest** [comment]
The parser doesn't currently support quotation marks as part of symbol syntax. Marking this as an "enhancement" and adding it to my todo list.

**Comment by JohnEarnest** [comment]
Looking into this further, it appears that the official K5 interpreter does not support this quoted symbol syntax:

```
 `"a long symbol"
ERROR: rank
 `"abc"
ERROR: rank
```

oK aims to be compatible with K5 wherever possible, so it looks like this syntax will not be implemented.

**Comment by muratg** [comment]
How about `$"hello"?

**Comment by JohnEarnest** [comment]
The behavior of `$` has changed. Rather than accepting a prototype, as in K4, There are a series of special symbols which can be used as left arguments to perform various conversions:

```
  `$"foo"
ERROR: type

 `i$"foo bar"
102 111 111 32 98 97 114

 `c$97+!5
"abcde"
```

As far as I can tell there isn't an equivalent of your example which permits casting a string to a symbol.

**Comment by muratg** [comment]
Ok (heh), thanks. Looks like K5 is a step down from K2 in some ways which is unfortunate.
